[django]
debug = false
secret_key = 'your-super-secret-key'
allowed_hosts = ['host.docker.internal', 'localhost']
time_zone = 'America/Denver'

[general]
min_uid = 1000
permissive_mode = false

[email]
notify_users = true
host = 'your.mail.server.edu'
port = '25'
lookup_function = 'your.python.function'

[prometheus]
url = 'https://your.prometheus.host:9090'
verify_ssl = true
user = 'username'
password = 'your-super-secret-password'

[warden]
job = 'cgroup-warden'
port = '2112'
bearer = 'your-super-secret-token'
verify_ssl = true
use_tls = true